# Generated by Django 5.2.7 on 2026-02-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0002_curso_adjunto_curso_profesor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                (
                    "especialidad",
                    models.IntegerField(
                        choices=[
                            (1, "Python"),
                            (2, "HTML"),
                            (3, "JavaScript"),
                            (4, "Django"),
                            (5, "C"),
                        ]
                    ),
                ),
            ],
        ),
    ]
