# Generated by Django 5.2.7 on 2026-02-05 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0003_profesor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name": "Profesor", "verbose_name_plural": "Profesores"},
        ),
        migrations.AddField(
            model_name="profesor",
            name="fecha_nacimiento",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
