# Generated by Django 5.2.7 on 2026-02-19 22:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Compañía",
                "verbose_name_plural": "Compañías",
            },
        ),
        migrations.AlterModelOptions(
            name="gender",
            options={
                "ordering": ["name"],
                "verbose_name": "Género",
                "verbose_name_plural": "Géneros",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["name"],
                "verbose_name": "Película",
                "verbose_name_plural": "Películas",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Sinopsis"
            ),
        ),
    ]
